#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bsd8st
ASM_TO_OBJS     = manager.asm
UI_TO_RDFS      =
SRCS            = bsError.asm bsInit.asm bsInt.asm bsVoice.asm manager.asm\
                  bsDelay.asm bsStream.asm bsStrate.asm bsMixer.asm\
                  bsDAC.asm bsTimer.asm bsWav.asm bsNWav.asm bsRecord.asm\
                  bsRegs.asm bsError.def bsConst.def
OBJS            = manager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
